Add alter routine load description docs
StarRocks/docs.zh-cn pull request #229
Opened 2022-01-22 07:57 UTC by gengjun-git

1. add alter routine load description docs.
2. change some format of ROUTINE LOAD.md

2022-01-22 08:00 UTC, Dshadowzh commented
Is this feature merged into 2.1?

2022-01-22 08:07 UTC, gengjun-git commented
> Is this feature merged into 2.1?

I will merge it into 2.1 after reviewing the code.  https://github.com/StarRocks/starrocks/pull/3018

2022-02-08 03:29 UTC, jaogoy requested changes

2022-02-08 03:29 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
> +1. `[db.]job_name`
不是目录，不是代码，就不用` 来括起来，需要的话可以用** 来加粗

2022-02-08 03:29 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/alter-routine-load.md
> +        1. 映射列：
这个是不是有个最全的说明，这里只是简述的话，可以在下面给出最全说明的链接。
如果有一些特殊限制，需要在这里说明下

2022-02-08 03:29 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/alter-routine-load.md
> +            以 col_name = expr 的形式表示的列，我们称为衍生列。即支持通过 expr 计算得出目的表中对应列的值。
为啥要把文字也放进```里？
和上面“映射列”的格式不大一样啊

2022-02-08 03:29 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/alter-routine-load.md
> +        ```plain text
格式问题，同上

2022-02-08 03:29 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/alter-routine-load.md
> +            COLUMNS (k2, k1, xxx, v1)
这个 SQL 应该是语法的一部分，不应该只是个举例，应该把完整的语法也列出来，比如：

COLUMNS ( [ <column_name> [, ...] ] [, column_assignment [, ...]  ])

column_assignment:
<column_name> = column_expression

（可以把这部分都放在上面的「语法」部分，可以参考 https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#syntax）

2022-02-18 08:44 UTC, merged