[WIP] json functions: json_array, json_object
StarRocks/docs.zh-cn pull request #249
Opened 2022-02-08 06:45 UTC by mofeiatwork

Write document for json functions `json_object` and `json_array`.

2022-02-21 05:49 UTC, kangkaisen submitted a review, later dismissed

2022-02-22 06:56 UTC, jaogoy requested changes

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-statements/data-types/JSON.md
> +- [json_parse](/sql-reference/sql-functions/json-functions/parse_json.md)
parse_json

2022-02-22 06:56 UTC, jaogoy commented on TOC.md
> +    + JSON函数
建议搞个 json 函数汇总页，介绍哪几类，就像 BigQuery 那样

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/parse_json.md
> +从JSON字符串解析出JSON对象。
是不是可以统计叫做”JSON 格式的字符串“，英文为 JSON-format string, 你可以其他地方看下，是不是这样的。
后面全文都这样写，会清晰一些

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-statements/data-types/JSON.md
> +在此基础上，借助Starrocks的向量化引擎，使用JSON类型能够对灵活的数据，进行高效的分析。
后续的函数会用到 number、string、bool、null 等特殊 JSON 类型，这块你看其他系统是怎么介绍的，可以简单介绍下，从而后面在区分 JSON 类型还是 SQL 类型时，就会比较清楚

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/parse_json.md
> +JSON对象的string需要用双引号括起来，遵循JSON标准，而JSON字符串需要用单引号。
”双引号“？你下面的都”单引号“

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `JSON json_object(varchar field_name, any field_value, ...)`
这里的类型，要不先统一都大写？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `JSON json_object(varchar field_name, any field_value, ...)`
这里的 any 是什么？一种类型么，还是只是一种表示方式？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_object.md
> +mysql> select json_object('name', 'starrocks', 'active', true, 'published', 2020);
再增加几个 example：
1. 有层级的JSON；
2. 可以有嵌套 JSON 的，甚至 json_array()；

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `ANY field_value`: JSON字段值，允许double/float/integer/varchar/char等类型
这些类型，是 JSON 类型，还是 SQL 类型，可以说明一下。
我们这些类型的统一大写吧。

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_array.md
> +JSON值，允许integer/double/float/varchar/char等类型
允许 JSON Object 或 JSON Array 么？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_exists.md
> +查询JSON对象中是否存在某个字段。
用”判断“两字是不是更好些？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_exists.md
> +- `json_path`: json_path, JSON对象中的路径。须为varchar类型
json_path， 重复了

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_exists.md
> +- `document JSON`: JSON对象, 须为JSON类型
1. 你其他地方是 `JSON document`这种 JSON 字在前的，保持统一下；
2. 支持的类型是 JSON，”须为 JSON 类型“就重复了；

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_exists.md
> +返回类型为 BOOL，表示JSON对象中是否存在某个字段。
”表示JSON对象中是否存在某个字段”， 这个在「功能」里都描述了，也不用重复了

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_exists.md
> +-- 查询JSON对象中是否存在 $.a.b 的字段, 结果为存在
这里能省略`$.`么？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_exists.md
> +mysql> select json_exists(parse_json('{"a": {"b": 1}}'), '$.a.c') ;
如果这里 path 和类型不对应，会怎样呢？
1. path 里是 a.c[1], 但数据里是 JSON Object；
2. 反过来；

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- `CAST(JSON json AS VARCHAR/INTEGER/BOOLEAN/DOUBLE/FLOAT)`: 将JSON转为SQL类型
我们”数字类型“，”字符串类型“都有具体具体的几种类型，你这里是不支持 TINYINT 等么？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- `CAST(VARCHAR/INTEGER/BOOLEAN/DOUBLE/FLOAT AS JSON)`: 将SQL类型转为JSON类型
SQL 类型后没有具体字段名

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- 如果类型不兼容，例如将数值类型转成字符串，会返回NULL
”不兼容“，是否给出一个兼容表格或说明？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- 对于SQL的NULL类型，不会转为JSON中的NULL类型，仍然为SQL中的NULL
1. 建议参考下其他文档，统一写 JSON 的 null 类型（全小写，或其他形式？）
2. 为什么这个特殊，不能转成 JSON 类型中的 null 类型？（后续可能还会实现 json_type(...)这种返回具体类型的函数）

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_cast.md
> +JSON类型可以通过CAST函数实现与其他SQL类型的转换。
还可以加：可以通过 CAST(...)函数，将 JSON 转化成 JSON-format 字符串

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_query.md
> +JSON, JSON_ARRAY
JSON_QUERY

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-statements/data-types/JSON.md
> +当前JSON支持以下函数和类型转换：
json_predicate.md 没有放进来

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +mysql> select parse_json('{"a": {"b": 1}}') -> '$.a.b';
可以省略外层引号么？因为：
1. key 都是 string；
2. 如果是数组，数组内只能是数字；

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +2. 如果运算符两边类型相同，且是复合类型(Object, Array)，按照元素逐个比较
{"a": 1, "c": 2}, {"b": 1, "a": 2} 这算类型相同么？那怎么个阻隔元素比较？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_path.md
> +- 数组片段：`$.a[1:3]`, 查询数组中的多个元素
数组片段，返回的是个什么类型？SQL Array ？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_path.md
> +```
没有写”关键字“

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_path.md
> +| json_query(parse_json('{"a": [{"b": 1}, {"b": 2}, {"b": 3}] }'), '$.a[1:3].b') |
如果数组中每个元素还是个 JSON Object，这里是个什么？

2022-02-22 06:56 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +```
”关键字“

2022-02-22 07:11 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_array.md
> +构造JSON数组。
done

2022-02-22 07:12 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +
done

2022-02-22 07:16 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +mysql> select parse_json('{"a": "b"}') -> 'a';
done

2022-02-22 07:19 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +如果查询的字段存在，则返回查询出的JSON值，否则返回NULL。
现在的 arrow + cast 已经实现了 json_value 的功能了，json_value的价值似乎不大？可

2022-02-22 08:01 UTC, mofeiatwork commented on sql-reference/sql-statements/data-types/JSON.md
> +  `id` INT(11) NOT NULL COMMENT "",
done

2022-02-22 08:03 UTC, mofeiatwork commented on sql-reference/sql-statements/data-types/JSON.md
> +-- 按照JSON过滤
1. done
2. 可以，但规则得梳理一下

2022-02-22 08:06 UTC, mofeiatwork commented on sql-reference/sql-statements/data-types/JSON.md
> +对于Parquet文件的导入，目前Starrocks能够支持其中部分数据类型的转换：
是特殊的。

对于Parquet里的Map、List、Struct等类型，目前只能导入JSON列，Starrocks不支持Map、List、Struct等类型。

2022-02-22 08:07 UTC, mofeiatwork commented on sql-reference/sql-statements/data-types/JSON.md
> +对于Parquet的MAP、STRUCT类型，会转换为JSON Object；对于LIST类型，会转换为JSON Array。
不能。Parquet导入目前没有这么高级。

2022-02-22 08:14 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_cast.md
> +# JSON 类型转换
done

2022-02-22 08:14 UTC, mofeiatwork commented on sql-reference/sql-statements/data-types/JSON.md
> +- [json_parse](/sql-reference/sql-functions/json-functions/parse_json.md)
done

2022-02-22 08:28 UTC, mofeiatwork commented on TOC.md
> +    + JSON函数
Done. 见 sql-reference/sql-functions/json-functions/json_functions.md

2022-02-22 08:29 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/parse_json.md
> +从JSON字符串解析出JSON对象。
done

2022-02-22 08:32 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/parse_json.md
> +JSON对象的string需要用双引号括起来，遵循JSON标准，而JSON字符串需要用单引号。
这里指的是 JSON对象里的：`parse_json('"star"'), parse_json('{"star": "rocks"}')`，JSON里的字符串需要用双引号。

2022-02-22 08:33 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `JSON json_object(varchar field_name, any field_value, ...)`
any 表示 INT/String/Bool 各种类型。

2022-02-22 08:35 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_object.md
> +mysql> select json_object('name', 'starrocks', 'active', true, 'published', 2020);
done

2022-02-22 08:36 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `ANY field_value`: JSON字段值，允许double/float/integer/varchar/char等类型
done

2022-02-22 08:37 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_array.md
> +JSON值，允许integer/double/float/varchar/char等类型
允许，改了

2022-02-22 08:38 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_exists.md
> +查询JSON对象中是否存在某个字段。
done

2022-02-22 08:38 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_exists.md
> +- `json_path`: json_path, JSON对象中的路径。须为varchar类型
done

2022-02-22 08:40 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_exists.md
> +- `document JSON`: JSON对象, 须为JSON类型
done

2022-02-22 08:41 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_exists.md
> +返回类型为 BOOL，表示JSON对象中是否存在某个字段。
done

2022-02-22 08:41 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_exists.md
> +-- 查询JSON对象中是否存在 $.a.b 的字段, 结果为存在
可以

2022-02-22 08:42 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_exists.md
> +mysql> select json_exists(parse_json('{"a": {"b": 1}}'), '$.a.c') ;
返回 false

2022-02-22 08:44 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- `CAST(JSON json AS VARCHAR/INTEGER/BOOLEAN/DOUBLE/FLOAT)`: 将JSON转为SQL类型
支持所有整数类型(INTEGER): TINYINT/SMALLINT/INT/BIGINT/LARGTINT ，全写感觉太繁琐了

2022-02-22 08:44 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- `CAST(VARCHAR/INTEGER/BOOLEAN/DOUBLE/FLOAT AS JSON)`: 将SQL类型转为JSON类型
done

2022-02-22 08:46 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- 如果类型不兼容，例如将数值类型转成字符串，会返回NULL
done

2022-02-22 08:48 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +mysql> select parse_json('{"a": {"b": 1}}') -> '$.a.b';
不能，，因为 parse_json 的参数是个字符串；省略引号其实就是 json_object 了

2022-02-22 08:49 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_path.md
> +- 数组片段：`$.a[1:3]`, 查询数组中的多个元素
done

2022-02-22 11:55 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +2. 如果运算符两边类型相同，且是复合类型(Object, Array)，按照元素逐个比较
你举的例子都是Object类型，比较规则如下：
1. 定义 left = `{"a": 1,  "c": 2}`, right = `{"b": 1, "a": 2}`
2. 遍历left，并在 right 查找
  1. field a: 在right 能找到，且 1 < 2 ；则返回结果 left < right
  2. 假如field相同，对比下一个field

2022-02-22 12:59 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-types/JSON.md
> +- 当前 JSON 类型不能直接用于 ORDER BY、GROUP BY、JOIN 计算，可转为 SQL 类型计算
是不是可以补充下可以使用CAST函数转换

2022-02-22 13:12 UTC, hellolilyliuyi commented on sql-reference/sql-functions/json-functions/json_query.md
> +`JSON json_query(JSON doc, VARCHAR json_path)`
建议数据类型放在参数说明中，无需放在语法中，使语法更加简洁直观。

2022-02-22 13:18 UTC, hellolilyliuyi commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `JSON doc`: 查询的 JSON 对象，可以为列引用，或通过 `parse_json` 等函数构造的 JSON 对象
JSON 类型、JSON对象、JSON doc等定义都是一致吗？如果是 是否可以统一定义描述。

2022-02-22 13:19 UTC, hellolilyliuyi commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `VARCHAR json_path`: JSON 对象中的查询路径
建议附上查询路径的文档链接

2022-02-23 09:22 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_path.md
> +| json_query(parse_json('{"a": [{"b": 1}, {"b": 2}, {"b": 3}] }'), '$.a[1:3].b') |
如果是Object，那就返回Object；总之就是构造一个数组，把匹配的元素都放进去

2022-02-23 09:26 UTC, mofeiatwork commented on sql-reference/sql-statements/data-types/JSON.md
> +- 当前 JSON 类型不能直接用于 ORDER BY、GROUP BY、JOIN 计算，可转为 SQL 类型计算
done

2022-02-23 09:37 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +`JSON json_query(JSON doc, VARCHAR json_path)`
Fine

2022-02-23 09:38 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `JSON doc`: 查询的 JSON 对象，可以为列引用，或通过 `parse_json` 等函数构造的 JSON 对象
Done

2022-02-23 09:43 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `VARCHAR json_path`: JSON 对象中的查询路径
done

2022-02-24 09:41 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `field_value`: JSON 字段值；支持 INTEGER/DOUBLE/FLOAT/VARCHAR/CHAR SQL 类型，以及 JSON 类型
是指 TINYINT 等就不支持么？

2022-02-24 09:41 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_path.md
>  - 数组提取：`$.a[*].b`，可以提取数组中的对象
这个是返回啥呢？也是JSON Array？

2022-02-24 09:41 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +2. 如果运算符两边类型相同，且是复合类型(Object, Array)，按照元素逐个比较
json 本身是没有排序的，也就是，如果是 Object 的，先将 key 排序，再先 key 再 value 的形式比较？
那你把这个 case 直接放进去吧，可以是 left= {"a": 1, "c": 2}, right = {"b": 1, "a": 1} 比较

2022-02-24 09:41 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/parse_json.md
> +JSON 对象的 string 类型需要用双引号括起来，遵循 JSON 标准，例如 `parse_json('"starrocks"')`。而 JSON 格式的字符串需要用单引号。
其他产品的实现，也是必须单引号么？（需要尽量保持标准或起其他产品兼容）
可以这样么？ "{\"a\":1, \"b\":\"1234\"}"
甚至 "{""a"":1, ""b"":""1234""}"  （这里用两个引号来表示转义）

2022-02-24 09:41 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_query.md
> +其中，JSON 类型支持以下几种子类型：
这段放 json.md 文件中吧

2022-02-24 09:41 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_query.md
> +- Bool: 布尔类型，支持 `true` 或 `false1
false1

2022-02-24 10:28 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_cast.md
> +- 如果JSON的数值类型转为更窄的SQL数值类型，会存在溢出问题
溢出返回NULL，和其他的CAST行为一致

2022-02-24 10:29 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +- Bool: 布尔类型，支持 `true` 或 `false1
done

2022-02-24 10:33 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +其中，JSON 类型支持以下几种子类型：
done

2022-02-24 10:35 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/parse_json.md
> +JSON 对象的 string 类型需要用双引号括起来，遵循 JSON 标准，例如 `parse_json('"starrocks"')`。而 JSON 格式的字符串需要用单引号。
这个主要是因为我们兼容MySQL协议，MySQL规定了字符串怎么转义。

JSON规定了需要用双引号括起来，而MySQL规定单引号里的双引号不用转义，所以这种写法最简单。

2022-02-24 10:36 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_path.md
>  - 数组提取：`$.a[*].b`，可以提取数组中的对象
en

2022-02-24 10:37 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `field_value`: JSON 字段值；支持 INTEGER/DOUBLE/FLOAT/VARCHAR/CHAR SQL 类型，以及 JSON 类型
这里的INTEGER指的是所有整数类型，，TINYINT/SMALLINT/INT/BIGINT/LARGEINT

2022-02-24 10:37 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_functions.md
> +## 关键词
done

2022-02-24 10:38 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +Starrocks 支持的 JSON Path 的语法请参考 [JSON Path 语法](/sql-reference/sql-functions/json-functions/json_path.md)。
done

2022-02-24 10:39 UTC, mofeiatwork commented on sql-reference/sql-functions/cast.md
> +除此之外，JSON 数据类型也可以支持转换，JSON 中的 Number/String/Bool 可以转换成 SQL 中的类型。细节可参考 [JSON 类型转换](sql-reference/sql-functions/json-functions/json_cast.md)。
done

2022-02-24 10:41 UTC, mofeiatwork commented on TOC.md
> ++ [StarRocks 介绍](/introduction/StarRocks_intro.md)
done

2022-02-24 10:51 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +2. 如果运算符两边类型相同，且是复合类型(Object, Array)，按照元素逐个比较
done

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_array.md
> +  - 允许 INTEGER/DOUBLE/FLOAT/VARCHAR/CHAR 等 SQL 类型
我们有具体的 TINYINT、VARCHAR 等类型，也有数字、字符串、日期等分类，这里建议说清楚，一个“等”字不太好

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +- 如果查询的字段不存在，返回 NULL，否则返回查询出的 JSON，其值类型可以是 Object/Array/Number/String/Boolean/Null。
“子类型”？
其他产品里，是怎么叫 JSON 内的具体数字、null 这些类型的？

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `field_value`: JSON 字段值；支持 INTEGER/DOUBLE/FLOAT/VARCHAR/CHAR SQL 类型，以及 JSON 类型
那你这里只是 STRING 么？
以及 DATE、DATETIME 的支持么？

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +3. 对于 field a: 在 right 能找到，且其 value `1 < 2` ；则返回结果 `left < right`
中文里叫“字段”吧？

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `doc`: 查询的 JSON，可以为列引用，或通过 `parse_json` 等函数构造的 JSON Object/Array；支持 JSON 类型
parse_json('"abc"') 这是算 JSON 的 String 类型？还是叫 JSON Object，我也有些迷糊了

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `json_path`: JSON 中的查询路径；支持 VARCHAR 类型；语法参考 [JSON Path](/sql-reference/sql-functions/json-functions/json_path.md)
用相对路径吧

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/parse_json.md
> +JSON 对象的 string 类型需要用双引号括起来，遵循 JSON 标准，例如 `parse_json('"starrocks"')`。而 JSON 格式的字符串需要用单引号。
OK，只要大致通用，或标准，或兼容 MySQL 就比较好

2022-02-25 02:10 UTC, jaogoy commented on sql-reference/sql-statements/data-types/JSON.md
> +- 当前 JSON 类型不能直接用于 ORDER BY、GROUP BY、JOIN 计算，可使用 CAST 函数转为 SQL 类型计算，参考 [JSON 类型转换](/sql-reference/sql-functions/json-functions/json_cast.md)
用相对路径吧

2022-02-25 02:28 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `doc`: 查询的 JSON，可以为列引用，或通过 `parse_json` 等函数构造的 JSON Object/Array；支持 JSON 类型
这是个JSON String，因为双引号括起来了。

2022-02-25 02:28 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +- `json_path`: JSON 中的查询路径；支持 VARCHAR 类型；语法参考 [JSON Path](/sql-reference/sql-functions/json-functions/json_path.md)
done

2022-02-25 02:30 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_predicate.md
> +3. 对于 field a: 在 right 能找到，且其 value `1 < 2` ；则返回结果 `left < right`
done

2022-02-25 02:31 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_arrow.md
> +- 如果查询的字段不存在，返回 NULL，否则返回查询出的 JSON，其值类型可以是 Object/Array/Number/String/Boolean/Null。
JSON sub type

2022-02-25 02:31 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_array.md
> +  - 允许 INTEGER/DOUBLE/FLOAT/VARCHAR/CHAR 等 SQL 类型
done

2022-02-25 02:33 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_object.md
> +- `field_value`: JSON 字段值；支持 INTEGER/DOUBLE/FLOAT/VARCHAR/CHAR SQL 类型，以及 JSON 类型
暂不支持。

2022-02-28 03:19 UTC, jaogoy approved these changes

2022-02-28 06:43 UTC, LittleBeeBee submitted a review, later dismissed

2022-03-02 08:34 UTC, colorfulu commented on sql-reference/sql-functions/json-functions/json_query.md
> +-- 查询JSON对象中的 a 数组的第二个元素，返回 JSON 类型的 3
这里应该是“第三个元素”

2022-03-02 08:35 UTC, colorfulu commented on sql-reference/sql-functions/json-functions/json_query.md
> +-- 查询JSON对象中的 a 数组的第三个元素，由于不存在，返回NULL
这里应该是“第四个元素”

2022-03-03 02:58 UTC, jaogoy requested changes

2022-03-03 02:58 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_path.md
> +- 数组元素查询：`$.a[1]`, 可以查询某个数组元素
这个下标是从 0 开始么？这里需要突出下

2022-03-03 02:58 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_path.md
> +- 数组片段：`$.a[1:3]`, 查询数组中的多个元素，返回 JSON Array
这个含义是什么 1 到 3 么，还是 从 1 开始，取 3 个？

2022-03-03 02:58 UTC, jaogoy commented on sql-reference/sql-functions/json-functions/json_query.md
> +-- 查询JSON对象中的 a 数组的第二个元素，返回 JSON 类型的 3
我们一般会说第〇个么？如果不会，可能就需要是第三个了

2022-03-03 08:08 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_query.md
> +-- 查询JSON对象中的 a 数组的第二个元素，返回 JSON 类型的 3
额，，编程语言里的数组下表都是从0开始的，，刻意翻译成『三』更容易引起混淆吧

2022-03-03 08:09 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_path.md
> +- 数组元素查询：`$.a[1]`, 可以查询某个数组元素
ok，基本都是默认的，，我强调一下吧

2022-03-03 08:10 UTC, mofeiatwork commented on sql-reference/sql-functions/json-functions/json_path.md
> +- 数组片段：`$.a[1:3]`, 查询数组中的多个元素，返回 JSON Array
数组切片的语法，，从 1 到 3 的左闭右开区间，

2022-03-03 08:20 UTC, colorfulu commented on sql-reference/sql-functions/json-functions/json_query.md
> +-- 查询JSON对象中的 a 数组的第二个元素，返回 JSON 类型的 3
可以跟你其他地方的描述保持一致，下标为二的元素

2022-03-22 08:06 UTC, jaogoy approved these changes

2022-04-27 15:17 UTC, closed without merging