add doc for array_agg
StarRocks/docs.zh-cn pull request #253
Opened 2022-02-09 02:27 UTC by trueeyu

2022-02-09 09:39 UTC, kangkaisen submitted a review, later dismissed

2022-02-14 04:59 UTC, Dshadowzh commented
索引文件 加一下这两个文件链接

2022-02-14 09:59 UTC, Dshadowzh submitted a review, later dismissed
LGTM

2022-02-24 08:39 UTC, jaogoy requested changes

2022-02-24 08:39 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/array_agg.md
> +# array_agg
不需要搞两个一样的文件啊，一个文件，上面 2 个链接即可

2022-04-07 03:11 UTC, trueeyu commented on sql-reference/sql-functions/aggregate-functions/array_agg.md
> +# array_agg
Fixed

2022-04-07 03:14 UTC, hellolilyliuyi approved these changes

2022-04-07 10:32 UTC, jaogoy approved these changes

2022-04-20 12:04 UTC, merged