Hive外表，增加开启ACL的HADOOP集群的配置描述
StarRocks/docs.zh-cn pull request #259
Opened 2022-02-10 11:27 UTC by winfys

PTAL

2022-02-10 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StarRocks/docs.zh-cn?pullRequest=259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StarRocks/docs.zh-cn?pullRequest=259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StarRocks/docs.zh-cn?pullRequest=259) it.</sub>

2022-02-17 08:22 UTC, gengjun-git commented
hello @winfys ，感谢贡献。这一段的内容已经很多了，能再加一段单独对ACL的说明吗？就像kerberos那样。

2022-02-19 12:23 UTC, jaogoy requested changes

2022-02-19 12:23 UTC, jaogoy commented on using_starrocks/External_table.md
> +* fe配置文件路径为fe/conf，如果需要自定义hadoop集群的配置可以在该目录下添加配置文件，例如：hdfs集群采用了高可用的nameservice，需要将hadoop集群中的hdfs-site.xml放到该目录下，如果hdfs配置了viewfs，需要将core-site.xml放到该目录下,如果hadoop集群配置了ACL，需要在该目录下创建hadoop_env.sh文件，并添加exp
1. 中文内容请用”全角标点符号“，比如这里应该是`，`而不是`,`；
2. 中英文混排时，中英文间加空格；
3. 如`export HADOOP_USER_NAME=${USER}` 这种命令、文件或目录的路径等，增加反引号 `；

2022-11-07 02:43 UTC, closed without merging