add doc for array_distinct
StarRocks/docs.zh-cn pull request #266
Opened 2022-02-15 13:07 UTC by trueeyu

2022-02-16 00:42 UTC, jaogoy requested changes

2022-02-16 00:42 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_distinct.md
> +`ARRAY_AGG(array)`
array_distinct？

2022-02-16 01:42 UTC, trueeyu commented on sql-reference/sql-functions/array-functions/array_distinct.md
> +`ARRAY_AGG(array)`
Fixed

2022-02-16 02:33 UTC, Dshadowzh commented on sql-reference/sql-functions/array-functions/array_distinct.md
> +删除数组中的重复元素。
删除是不是有歧义，容易误解成把原始数组数据删除了，这里写获取数组元素的唯一值是不是更好

2022-02-16 02:33 UTC, Dshadowzh commented on sql-reference/sql-functions/array-functions/array_distinct.md
> +# array_distinct
记得加目录

2022-02-16 02:35 UTC, trueeyu commented on sql-reference/sql-functions/array-functions/array_distinct.md
> +删除数组中的重复元素。
写成数组元素去重， 怎么样？

2022-02-16 02:38 UTC, trueeyu commented on sql-reference/sql-functions/array-functions/array_distinct.md
> +# array_distinct
Fixed

2022-02-24 08:36 UTC, jaogoy approved these changes

2022-04-20 12:05 UTC, merged