Add Doc for retention
StarRocks/docs.zh-cn pull request #269
Opened 2022-02-16 07:50 UTC by Pslydhh

Add doc for aggregate function of retention.

2022-02-16 08:50 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +该函数将一个Array<BOOLEAN>作为参数，每个boolean表示某事件是否成立。
这个参数怎么会是个 boolean 呢，不应该是个“返回 boolean 的表达式“么

2022-02-16 08:50 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +mysql> SELECT retention([lo_orderdate = '1997-08-01' AND lo_orderpriority = '2-HIGH', lo_orderdate = '1997-08-02' AND
不要这么长的一行，分行格式化下？

2022-02-16 08:50 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +mysql> SELECT retention([lo_orderdate = '1997-08-01' AND lo_orderpriority = '2-HIGH', lo_orderdate = '1997-08-02' AND
并且，应该先给出一些数据，看得人才能从数据结合结果分析

2022-02-16 09:05 UTC, Pslydhh commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +该函数将一个Array<BOOLEAN>作为参数，每个boolean表示某事件是否成立。
是个Array，Array里面的内容只能是boolean。
我们通过 把返回 boolean 的表达式 作为array的元素，这样子来使用retention。

2022-02-16 09:05 UTC, Pslydhh commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +mysql> SELECT retention([lo_orderdate = '1997-08-01' AND lo_orderpriority = '2-HIGH', lo_orderdate = '1997-08-02' AND
好的，我按照模版修改下。

2022-02-24 08:32 UTC, jaogoy requested changes

2022-02-24 08:32 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +* input：一系列表示事件的表达式构成的Array，类型为Array\<BOOLEAN\>。
1. 需要反斜杠么，直接 Array<BOOLEAN>可以么？
2. 是 BOOLEAN 么，不应该是 BOOLEAN Expression 么？ 否则，我是不是可以把一个类型为 Array<BOOLEAN>的列作为参数写进来？

2022-02-24 08:32 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +mysql> SELECT retention([lo_orderdate = '1997-08-01' AND lo_orderpriority = '2-HIGH',
因为用的是 text 格式，建议这个长 sql 格式化些，类似：
mysql> SELECT retention([lo_orderdate = '1997-08-01' AND lo_orderpriority = '2-HIGH',
                                              lo_orderdate = '1997-08-02' AND lo_orderpriority = '1-URGENT',
                                              ...]) AS r
               FROM xxx
               
后面的也一起格式化下

2022-02-24 08:32 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +**case 1**:
统一为  示例一，示例二 吧

2022-02-24 08:32 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +计算满足条件lo_orderdate = '1997-08-02' AND lo_orderpriority = '1-URGENT'和满足条件
sql、路径 等，加反引号: `lo_order xxx`

2022-02-24 08:32 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +## 示例
这三个用例的目的分别是什么，有循序渐进的效果么？
感觉第三个例子应该是最容易理解的？

2022-02-25 06:39 UTC, Pslydhh commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +* input：一系列表示事件的表达式构成的Array，类型为Array\<BOOLEAN\>。
> 

1. 这里斜杠只是转义符，就是Array.
2. 现在的实现支持把Array的列作为参数来使用。只是我们提供retention的意图是让用户通过写BOOLEAN Expression来使用。没有区分这两种情况

2022-02-25 06:47 UTC, Pslydhh commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +## 示例
> 这三个用例的目的分别是什么，有循序渐进的效果么？ 感觉第三个例子应该是最容易理解的？

第一个和第二个就直接用。第三个是详细描述了语义。我把前两个例子删了吧，看第三个例子应该就懂了。

2022-02-28 03:15 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> +       retention([lo_orderdate='1022-11-20' AND lo_orderpriority='4-NOT SPECI',
注意下格式，一般相对 SELECT 头部再 4 空格缩进。下面的也要对齐缩进，清晰一些。

或者，除第一行外，都按正常顶格写的方式再缩进，那这里第二行应该是只缩进 4 空格，而不是 7 空格，下一行要缩进 8 空格，或对齐到 retentioni的第一个参数。

2022-02-28 03:15 UTC, jaogoy commented on sql-reference/sql-functions/aggregate-functions/retention.md
> ++------------+-----------+
你这里只有两列结果，对于 retention 的说明还不够到位，至少是 3 个。所以之前的 case 建议保留

2022-03-07 10:30 UTC, jaogoy approved these changes
我调整了点格式，你看这样是否更好些

2022-03-08 10:03 UTC, Pslydhh commented
> 我调整了点格式，你看这样是否更好些

好的，现在已经通过check了。

2022-04-05 12:05 UTC, jaogoy approved these changes

2022-04-06 08:14 UTC, Yuchen914 approved these changes
LGTM

2022-04-20 12:06 UTC, merged