Update DataX and Flink plugins
StarRocks/docs.zh-cn pull request #28
Opened 2021-09-17 10:42 UTC by Dshadowzh

2021-09-17 11:12 UTC, hffariel requested changes

2021-09-17 11:12 UTC, hffariel commented on loading/DataX-starrocks-writer.md
> +  * 描述：目的表需要写入数据的字段,字段之间用英文逗号分隔。例如: "column": ["id","name","age"]。
这里支持填入["*"] 了

2021-09-17 11:12 UTC, hffariel requested changes

2021-09-17 11:12 UTC, hffariel commented on loading/Flink-connector-starrocks.md
>  ```plain text
plain text -> xml

2021-09-18 03:23 UTC, jaogoy commented on loading/Flink-connector-starrocks.md
> +            .withProperty("jdbc-url", "jdbc:mysql://ip:port,ip:port?xxxxx")
改回去吧

2021-09-18 03:35 UTC, Dshadowzh commented on loading/DataX-starrocks-writer.md
> +  * 描述：目的表需要写入数据的字段,字段之间用英文逗号分隔。例如: "column": ["id","name","age"]。
fixed

2021-09-18 04:50 UTC, Dshadowzh commented on loading/Flink-connector-starrocks.md
> +            .withProperty("jdbc-url", "jdbc:mysql://ip:port,ip:port?xxxxx")
fixed

2021-09-19 14:45 UTC, jaogoy commented on loading/DataX-starrocks-writer.md
> +  * 描述：StarRocks数据库的用户名
我建议，一般情况下，英文单词左右都统一保留空格

2021-09-22 04:13 UTC, jaogoy approved these changes

2021-09-22 05:55 UTC, hffariel approved these changes

2021-09-22 05:57 UTC, merged