Create CREATE TABLE AS SELECT.md
StarRocks/docs.zh-cn pull request #289
Opened 2022-02-22 11:52 UTC by hellolilyliuyi

2022-02-23 07:37 UTC, jaogoy requested changes

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +
这里不需要空行

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +| partition_desc   | 分区方式。更多说明，请参见[数据分布](../table_design/Data_distribution.md)。如果不填写，则默认为无分区。 |
../../../table_design
注意这里的目录层级

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +| 参数             | 说明                                                         |
这个我觉得不需要表格，我觉得可以参看 Snowflake 的 sql reference

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +| partition_desc   | 分区方式。更多说明，请参见[数据分布](../table_design/Data_distribution.md)。如果不填写，则默认为无分区。 |
并且，我们这里是着重语法解释，不是原理介绍，所以得参考其他前面描述 partition_desc 的语法和参数含义的部分

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +- 暂无法对 CTAS 提供事务保证。
会产生什么问题，可以补充下

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +- 暂不支持设置索引。
这种标号的，句末是句号还是分号，有统一么？

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +支持`AS SELECT <query>` 直接指定具体列，比如 `as select a, b, c from table_a;` ，则新建表的列名为a，b， c 。
可以改成 ”比如 `... AS SELECT a, b, c FROM table_a;`“
1. 这里的 SQL 不完成，可以把没有的部分用...代替；
2. SQL 的关键字头统一大写是否 OK；

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +create table order_new as select * from order;
我建议，这里的都拆成多行（格式化下）
这里的 as select ... 部分都换新行

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +示例三：AS SELECT *<query>*使用表达式，根据表达式结果，创建一个新表，并重新指定列名。
AS SELECT *<query>*
这部分这里的 view 是  AS SELECT ** ，你 check 下。
并且可以加反引号 `AS SELECT *<query>*`

2022-02-23 07:37 UTC, jaogoy commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +START ("1993-01-01") END ("1999-01-01") EVERY (INTERVAL 1 YEAR)
注意缩进格式

2022-02-23 11:45 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +| 参数             | 说明                                                         |
表格能更清晰展现内容。这个设计sql语句模版的时候 同一个展现形式吧

2022-02-23 11:46 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +| 参数             | 说明                                                         |
> 这个我觉得不需要表格，我觉得可以参看 Snowflake 的 sql reference

表格能更清晰展现内容。这个设计sql语句模版的时候 同一个展现形式吧

2022-02-23 11:46 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +- 暂不支持设置索引。
一般情况下统一为。

2022-02-23 13:44 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
> +- 暂无法对 CTAS 提供事务保证。
@Astralidea 辛苦看下这个问题

2022-02-24 07:34 UTC, jaogoy approved these changes

2022-02-24 08:06 UTC, merged