Add doc for array_slice/array_concat/array_difference/array_overlap/a…
StarRocks/docs.zh-cn pull request #297
Opened 2022-02-25 02:09 UTC by Pslydhh

Add doc for array_slice/array_concat/array_difference/array_overlap/array_intersect.

2022-03-19 06:04 UTC, jaogoy requested changes

2022-03-19 06:04 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_concat.md
> +* input：输入为不限数量的相同类型的数组(input0, input1, ...)。
需要说清楚 input 和 output 的参数类型，见我们的函数文档编写规范

2022-03-19 06:04 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_difference.md
> +对于数值型数组，返回相邻两个元素的差构成的数组。
是前减去后，还是后减前面的元素

2022-03-19 06:04 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_slice.md
> +* offset: 结果数组片段的起始偏移。
从 0 开始还是 1 开始

2022-04-05 12:09 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_concat.md
> +output array_concat(input)
你这里是1 到多个参数，原来的是 ok 的吧

2022-04-05 12:09 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_intersect.md
> +output array_intersect(input)
应该是 2 个及以上的参数吧

2022-04-05 12:09 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_slice.md
> +* offset: 结果数组片段的起始偏移(从1开始)。
数组的下标都是统一从 1 开始的么？

2022-04-07 03:06 UTC, Pslydhh commented on sql-reference/sql-functions/array-functions/array_concat.md
> +output array_concat(input)
下面解释input是由多个数组构成。这样子比较合适吧？

2022-04-07 03:07 UTC, Pslydhh commented on sql-reference/sql-functions/array-functions/array_intersect.md
> +output array_intersect(input)
> 应该是 2 个及以上的参数吧

1个也是可以的，结果是这个数组

2022-04-07 03:07 UTC, Pslydhh commented on sql-reference/sql-functions/array-functions/array_slice.md
> +* offset: 结果数组片段的起始偏移(从1开始)。
> 数组的下标都是统一从 1 开始的么？

是的

2022-04-07 10:34 UTC, jaogoy commented on sql-reference/sql-functions/array-functions/array_intersect.md
> +output array_intersect(input)
直接(input1, input2, ...) 然后说，可以1个或多个吧？
这样清晰

2022-04-07 13:14 UTC, jaogoy approved these changes

2022-04-20 12:05 UTC, merged