ldap认证新增ad
StarRocks/docs.zh-cn pull request #310
Opened 2022-03-03 05:50 UTC by 311709000529

2022-03-07 02:50 UTC, hellolilyliuyi commented on administration/Scale_up_down.md
> +* `alter system dropp backend "be_host:be_heartbeat_service_port";`
确定是“dropp”？不是“drop”？

2022-03-07 02:53 UTC, hellolilyliuyi commented on administration/Authentication.md
>  * authentication\_ldap\_simple\_bind\_root\_dn：检索用户时，使用的管理员账号DN。
上面这句“不指定DN的用户...则认证成功果”——删除“果”哈

2022-03-19 06:09 UTC, jaogoy commented on administration/Scale_up_down.md
> +* `alter system dropp backend "be_host:be_heartbeat_service_port";`
可以确定当前是 dropp 还是 drop force 了。
然后，这里我不建议直接放出来，有些用户容易直接拷贝黏贴

2022-04-06 11:43 UTC, jaogoy requested changes

2022-04-06 11:43 UTC, jaogoy commented on unloading/Export.md
> +JobId: 23004
自己修改后要 review pr 啊，这个格式搞回原来的

2022-04-22 09:55 UTC, hellolilyliuyi commented on using_starrocks/Array.md
>  下面简要介绍一些是使用方式，更详细的函数语法请查看 `参考手册 > 函数参考 > 数组函数`。
提供第一个数组的链接

2022-04-28 03:13 UTC, Yuchen914 approved these changes
seesee

2022-04-29 07:22 UTC, jaogoy commented on using_starrocks/Temporary_partition.md
> +    ```
是 sql 的加上 SQL 语法标志

2022-04-29 07:29 UTC, jaogoy commented on using_starrocks/Temporary_partition.md
> +临时分区旨在解决用户在使用 StarRocks 时，因为分区分桶不合理而导致的问题。
为了解决”分区分桶不合理而导致的问题“？

显然不是吧，你直接把最后的 3 中场景放这里，多好

2022-05-07 05:54 UTC, jaogoy commented on using_starrocks/Lateral_join.md
> +* 当前版本 Lateral join 仅用于和 Unnest 函数配合使用，实现行转列的功能，后续会支持其他 table function / UDTF。
有 UDTF 链接的话，可以加上

2022-05-07 05:54 UTC, jaogoy commented on using_starrocks/Window_function.md
>  function(args) OVER(partition_by_clause order_by_clause [window_clause])
我们当前 reference 中没有对窗口函数等整体的描述，导致具体的语法放在这里，有点划分得不清晰。
这块你和刘艺他们交流下。

2022-05-07 05:54 UTC, jaogoy commented on using_starrocks/Window_function.md
>  ### AVG()
这些函数，后续得都拆到 「函数参考」中。
记录一个 issue。

2022-05-09 02:02 UTC, closed without merging