Add user manual for hudi external table
StarRocks/docs.zh-cn pull request #312
Opened 2022-03-03 08:43 UTC by miomiocat

Add user manual for hudi external table

2022-03-15 08:11 UTC, jaogoy requested changes

2022-03-15 08:11 UTC, jaogoy commented on using_starrocks/External_table.md
> +
sql 代码中，不要这么些空行

2022-03-15 08:11 UTC, jaogoy commented on using_starrocks/External_table.md
> +
保持 4 空格缩进

2022-03-15 08:11 UTC, jaogoy commented on using_starrocks/External_table.md
> +"resource" = "hudi0",
有 resource，上面的 engine 还要 hudi，是为什么？如果改成 OLAP 、hive 等其他的，或有错误提示么？

2022-03-15 08:34 UTC, miomiocat commented on using_starrocks/External_table.md
> +请确认StarRocks有权限访问Apache Hudi对应的Hive Metastore、HDFS集群或者对象存储的Bucket。
一般都懂，跟hive外表一样

2022-03-15 08:37 UTC, miomiocat commented on using_starrocks/External_table.md
> +"type" = "hudi",
done

2022-03-15 08:37 UTC, miomiocat commented on using_starrocks/External_table.md
> +
done

2022-03-15 08:38 UTC, miomiocat commented on using_starrocks/External_table.md
> +"resource" = "hudi0",
有错误提示，这两个是分开的，各用各的，跟hive外表一样

2022-03-22 03:07 UTC, chaoyangqi submitted a review, later dismissed
clear!

2022-03-22 11:50 UTC, hellolilyliuyi approved these changes

2022-04-06 11:46 UTC, jaogoy requested changes

2022-04-06 11:46 UTC, jaogoy commented on using_starrocks/External_table.md
>  `id` bigint NULL,
内部 统一 4 空格缩进

2022-04-06 11:46 UTC, jaogoy commented on using_starrocks/External_table.md
>  `id` bigint NULL,
还有上面 476 行，一些不必要的空格去掉，缩进统一为 4 空格

2022-04-19 09:34 UTC, hellolilyliuyi approved these changes

2022-04-19 10:25 UTC, jaogoy approved these changes

2022-04-20 12:04 UTC, merged