hive metadata cache of fe automatic incremental synchronization doc
StarRocks/docs.zh-cn pull request #318
Opened 2022-03-08 10:46 UTC by stephen-shelby

2022-03-08 11:17 UTC, stephen-shelby commented
cc @gengjun-git

2022-03-08 11:29 UTC, gengjun-git commented on using_starrocks/External_table.md
> +  * 开启元数据自动增量更新机制后，`hive_meta_cache_refresh_interval_s`将不会生效。即FE中缓存不会自动异步刷新。
这里需要说吗？感觉会让用户有点晕，用户关心的是会不会更新，不用关心底层是如何实现的。

2022-03-08 11:32 UTC, gengjun-git commented on using_starrocks/External_table.md
> +  * 开启元数据自动增量更新机制后，`hive_meta_cache_refresh_interval_s`将不会生效。即FE中缓存不会自动异步刷新。
397这一行

2022-03-08 11:35 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  * 开启元数据自动增量更新机制后，`hive_meta_cache_refresh_interval_s`将不会生效。即FE中缓存不会自动异步刷新。
也是，反正也不生效，我删掉

2022-03-08 11:36 UTC, gengjun-git approved these changes
LGTM

2022-03-19 06:24 UTC, jaogoy requested changes

2022-03-19 06:24 UTC, jaogoy commented on using_starrocks/External_table.md
> +  > 如果为CSV格式，则暂不支持引号为转义字符。
为什么删除 2 个空格了？这个是缩进

2022-03-19 06:24 UTC, jaogoy commented on using_starrocks/External_table.md
> +   用户需要在$HiveMetastore/conf/hive-site.xml中添加如下配置，并重启Hive Metastore.
必须重启么？

2022-03-19 06:24 UTC, jaogoy commented on using_starrocks/External_table.md
> +    用户需要在$FE/conf/fe.conf中添加如下配置
统一为 $FE_HOME 吧

2022-03-19 06:24 UTC, jaogoy commented on using_starrocks/External_table.md
> +  * 不同版本Hive Metastore的Events事件可能不同，且上述开启HiveMetastore Event机制的配置在不同版本也存在不同。使用时相关配置可根据实际版进行适当调整。
那得给出你这里支持了哪几个版本

2022-03-19 06:24 UTC, jaogoy commented on using_starrocks/External_table.md
> +  * 当前Hive元数据缓存为懒加载，即如果新增分区，只会将新增分区的partition key进行缓存，不会缓存该分区的文件信息。只有实际查询该分区或者手动执行refresh分区，该分区文件缓存信息才会进行加载。分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。
“该分区文件缓存信息” 是指分区文件，还是分区的元信息？

2022-03-24 06:54 UTC, MarkovWangRR requested changes

2022-03-24 06:54 UTC, MarkovWangRR commented on using_starrocks/External_table.md
> +  * 不同版本Hive Metastore的Events事件可能不同，且上述开启HiveMetastore Event机制的配置在不同版本也存在不同。使用时相关配置可根据实际版进行适当调整。
或者说一下 上述文档中的开启方式 是以hive的2.X.X或者3.X.X版本为例

2022-03-24 06:54 UTC, MarkovWangRR commented on using_starrocks/External_table.md
> +  * 当前Hive元数据缓存为懒加载，即如果新增分区，只会将新增分区的partition key进行缓存，不会缓存该分区的文件信息。只有实际查询该分区或者手动执行refresh分区，该分区文件缓存信息才会进行加载。分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。
——> 当前Hive元数据缓存模式为懒加载，即：“如果HIVE新增了分区，**StarRocks**只会将新增分区的partition key进行缓存，不会**立即**缓存该分区的文件信息。只有当查询该分区时或者用户手动执行refresh分区操作时，该分区的文件信息才会被加载。

2022-03-24 06:54 UTC, MarkovWangRR commented on using_starrocks/External_table.md
> +  * 当前Hive元数据缓存为懒加载，即如果新增分区，只会将新增分区的partition key进行缓存，不会缓存该分区的文件信息。只有实际查询该分区或者手动执行refresh分区，该分区文件缓存信息才会进行加载。分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。
“分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。” 是不是需要从用户视角讲一下：我们设计的这个机制，对于用户来说能感知到的before&after是什么

2022-03-24 06:54 UTC, MarkovWangRR commented on using_starrocks/External_table.md
> +  * 当前Hive元数据缓存为懒加载，即如果新增分区，只会将新增分区的partition key进行缓存，不会缓存该分区的文件信息。只有实际查询该分区或者手动执行refresh分区，该分区文件缓存信息才会进行加载。分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。
沟通了一下，可以这么描述：“在StarRocks首次缓存该分区信息后，该分区后续的元信息变更就会自动同步到StarRocks中。”

2022-03-24 12:05 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  > 如果为CSV格式，则暂不支持引号为转义字符。
格式检查给的报错。

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  > 如果为CSV格式，则暂不支持引号为转义字符。
格式检查给的报错

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +   用户需要在$HiveMetastore/conf/hive-site.xml中添加如下配置，并重启Hive Metastore.
对，这个必须重启的。这是hive metastore的机制哈。

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +    用户需要在$FE/conf/fe.conf中添加如下配置
done

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  * 不同版本Hive Metastore的Events事件可能不同，且上述开启HiveMetastore Event机制的配置在不同版本也存在不同。使用时相关配置可根据实际版进行适当调整。
done

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  * 不同版本Hive Metastore的Events事件可能不同，且上述开启HiveMetastore Event机制的配置在不同版本也存在不同。使用时相关配置可根据实际版进行适当调整。
done

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  * 当前Hive元数据缓存为懒加载，即如果新增分区，只会将新增分区的partition key进行缓存，不会缓存该分区的文件信息。只有实际查询该分区或者手动执行refresh分区，该分区文件缓存信息才会进行加载。分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。
done

2022-03-24 12:51 UTC, stephen-shelby commented on using_starrocks/External_table.md
> +  * 当前Hive元数据缓存为懒加载，即如果新增分区，只会将新增分区的partition key进行缓存，不会缓存该分区的文件信息。只有实际查询该分区或者手动执行refresh分区，该分区文件缓存信息才会进行加载。分区缓存信息一旦加载，后续自动增量处理机制就会对已缓存的分区进行增量更新。
done

2022-03-28 12:18 UTC, MarkovWangRR approved these changes

2022-03-29 11:23 UTC, MarkovWangRR approved these changes

2022-03-29 11:23 UTC, MarkovWangRR approved these changes

2022-03-29 11:27 UTC, MarkovWangRR approved these changes

2022-03-29 11:51 UTC, hellolilyliuyi approved these changes

2022-04-06 11:49 UTC, jaogoy approved these changes

2022-04-20 12:07 UTC, merged