add upgrade docs
StarRocks/docs.zh-cn pull request #321
Opened 2022-03-09 03:06 UTC by stdpain

2022-03-10 02:34 UTC, chaoyli approved these changes

2022-03-10 02:35 UTC, merged

2022-03-10 02:40 UTC, jaogoy requested changes

2022-03-10 02:40 UTC, jaogoy commented on administration/Cluster_administration.md
> +StarRocks如果从2.0升级到2.1版本如果是灰度升级的方式需要确保下面的一些配置项:
你这里的灰度升级是指什么，是指同时存在高低版本的 BE，还是什么，说说清楚

2022-03-10 02:40 UTC, jaogoy commented on administration/Cluster_administration.md
> +1. 确保所有be的配置项vector_chunk_size是4096(默认配置)
BE、FE 这种专有名词，统一固定大些。
统一中英文边界加空格（你一些加了，一些没加）

2022-03-10 02:40 UTC, jaogoy commented on administration/Cluster_administration.md
> +```sql
有结果表格的，格式用 plain text（否则表格的格式会有些奇怪）

2022-03-10 02:40 UTC, jaogoy commented on administration/Cluster_administration.md
> +1. 确保所有be的配置项vector_chunk_size是4096(默认配置)
如果有不是的，是直接修改 BE 的 be.conf 后重启么？

2022-03-10 02:40 UTC, jaogoy commented on administration/Cluster_administration.md
> +mysql> set global batch_size = 4096;
你上面说“确保小于 4096”，这里是等于，矛盾啊

2022-03-10 02:40 UTC, jaogoy commented on administration/Cluster_administration.md
> +-- 设置 batch_size
多段语句间，加个空行，清晰一些

2022-03-21 06:25 UTC, stdpain commented on administration/Cluster_administration.md
> +1. 确保所有be的配置项vector_chunk_size是4096(默认配置)
需要重启

2022-03-21 06:25 UTC, stdpain commented on administration/Cluster_administration.md
> +mysql> set global batch_size = 4096;
<=