modify the memory classification
StarRocks/docs.zh-cn pull request #328
Opened 2022-03-14 04:29 UTC by trueeyu

2022-03-14 06:00 UTC, jaogoy requested changes

2022-03-14 06:54 UTC, trueeyu commented on administration/Memory_management.md
> +| query_pool | starrocks_be_column_pool_mem_bytes | BE 查询层使用总内存  | 默认为 process 内存的 90%，不支持修改 |
Fixed

2022-03-14 06:54 UTC, trueeyu commented on administration/Memory_management.md
> +| page_cache | starrocks_be_storage_page_cache_mem_bytes | BE 存储层 page 缓存 | 默认关闭，在内存充裕并且有大量数据扫描的场景可以考虑打开，可以加速查询性能 |
Fixed

2022-03-15 02:42 UTC, jaogoy approved these changes

2022-03-16 05:41 UTC, merged