Refactoring  Quick start
StarRocks/docs.zh-cn pull request #329
Opened 2022-03-14 06:43 UTC by dq1201

1.调整快速开始目录，新增“创建表“章节，隐藏不使用章节目录，仅保留”StarRocks基本概念及系统架构“，”StarRocks手动部署“，”创建表“，”数据导入和查询“。
2.将集群高可用配置移至”集群部署“章节。
3.调整”StarRocks基本概念及系统架构“，”StarRocks手动部署“，”数据导入和查询“章节的内容使得用户更易快速部署体验starrocks,并增加超链接方便用户深入了解starrocks。

2022-03-23 10:09 UTC, jaogoy requested changes
感觉比之前的清晰很多了

2022-03-23 10:09 UTC, jaogoy commented on quick_start/Create_table.md
> +```Plain Text
示例最好是可以直接照着做的，你这个可以搞成 INSERT INTO values()的形式，再 select。

所有其他示例也一样，都要求可以直接照着做，甚至是拷贝+黏贴就可以。

2022-03-23 10:09 UTC, jaogoy commented on quick_start/Import_and_query.md
> +curl --location-trusted -u root: -T detailDemo\_data -H "label: streamDemo" \ -H "column_separator:," \
注意换行（格式）

2022-03-23 10:09 UTC, jaogoy commented on quick_start/Import_and_query.md
> +* 通过 set is\_report\_success = true 可以打开profile的上报。
1. _ 不再需要 \_ 
2. 所有命令、path 等，都要用`xxx` 包起来

2022-03-23 10:09 UTC, jaogoy commented on quick_start/Import_and_query.md
> +* 企业版用户在StarRocksManager的查询页面可以看到图形化的Profille展示，点击查询链接可以在“执行时间“页面看到树状展示，可以在“执行详情“页面看到完整的Profile详细信息。如果达不到预期可以发送执行详情页面的文本到社区或者技术支持的群里寻求帮助
建议统一用「执行时间」这种，或者用粗体**执行时间**，“执行时间”这种引号方式就是普通的一些特殊，

2022-03-24 03:06 UTC, Dshadowzh commented on quick_start/Import_and_query.md
> +</br>
推荐删除这些显示的 html标记，这个应该没有展示效果吧？

2022-03-24 09:33 UTC, dq1201 commented on quick_start/Architecture.md
> +<img width="540px" height="400px" src="../assets/2.1-1.png"/>
我的想法是，图太大占篇幅，小一点可以让客户快速开始看文字部分。因此将图调到一个小但是细看可以看到内容的大小。

2022-03-24 11:20 UTC, dq1201 commented on quick_start/Import_and_query.md
> +2022-03-13,1,1212,1231231231,123412341234,123452342342343324,hello,welcome,starrocks,2022-03-15 12:21:32,123.04,21.12345,123456.123456,true
这个是为了和建表处对应，让客户可以使用同一个表导入数据进行查询验证，建表选用多字段是为了让客户在此处对我们支持的字段类型有个初步了解

2022-03-30 11:46 UTC, jaogoy commented on quick_start/Import_and_query.md
> +```Plain SQL
SQL

2022-04-01 03:05 UTC, hellolilyliuyi approved these changes

2022-04-01 03:27 UTC, jaogoy reviewed
注意自己看下 github 里的预览“View file”

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Create_table.md
> +```sql
这个其实是 shell 或 bash，不是 sql

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Deploy.md
> +* 使用浏览器访问 FE ip: http_port（默认8030）， 打开 StarRocks 的 WebUI， 用户名为 root， 密码为空。
`FE_ip:http_port` 这种和普通文字不大一样的，注意下格式，`ip:` 后和 port 间，不应该有空格

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Import_and_query.md
> +### 如何查看 Profile 并通过 Profile 分析查询瓶颈
“通过 Profile”这几个词就可以删掉了吧

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Deploy.md
>  * 如果 FE 启动失败，可能是由于端口号被占用，可修改配置文件 conf/fe.conf 中的端口号 http_port。
上面几行日志，中间就不要空行了

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Deploy.md
>  Ubuntu：sudo apt-get install mysql-client
命令，一般采用`xxx` 包起来

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Deploy.md
> +               IP: 172.16.139.11
下面一点的：
1. 一般情况下<br/>就不用了，我们最终文档和 github 预览会有一些差异；
2. Role、IsMaster 这种属于具体的 key，建议：
    a. 分行写；
    b. Role、IsMaster 这种 key 加粗；
    比如： **Role**：xxxx；

2022-04-01 03:27 UTC, jaogoy commented on quick_start/Deploy.md
> +               IP: 172.16.139.11
当然，如果只是挑很少的几个说明，不太注重格式，可能也还好

2022-04-01 06:58 UTC, hellolilyliuyi approved these changes

2022-04-01 07:04 UTC, jaogoy approved these changes

2022-04-01 07:17 UTC, merged