Add doc for sm3
StarRocks/docs.zh-cn pull request #330
Opened 2022-03-14 08:52 UTC by Pslydhh

Add document for sm3 function

2022-03-17 11:42 UTC, Dshadowzh approved these changes

2022-03-19 06:28 UTC, jaogoy requested changes

2022-03-19 06:28 UTC, jaogoy commented on sql-reference/sql-functions/encryption-functions/sm3.md
> +采用SM3密码杂凑算法来输出长度为256比特的杂凑值
杂凑 我们会用这个词么，不都 hash 或 散列 啥的么？

2022-03-19 06:28 UTC, jaogoy commented on sql-reference/sql-functions/encryption-functions/sm3.md
> +* message: 任意的字符串
加类型，参考函数编写规范
下同

2022-07-15 12:19 UTC, closed without merging