update routine load and spark load
StarRocks/docs.zh-cn pull request #371
Opened 2022-04-02 02:02 UTC by LittleBeeBee

2022-04-05 14:34 UTC, jaogoy commented on loading/RoutineLoad.md
> +**** **** **** **** **** **** *** 1. row *** **** **** **** **** **** ****
格式

2022-04-05 14:36 UTC, jaogoy commented on loading/RoutineLoad.md
> +### json 文本
适当说明下

2022-04-05 14:41 UTC, jaogoy commented on loading/SparkLoad.md
> +* `spark.master`: 必填，目前支持 yarn。
预览下格式，是否有问题

2022-04-06 07:57 UTC, LittleBeeBee commented on loading/SparkLoad.md
>  导入任务的标识。每个导入任务，都有一个在单 database 内部唯一的 Label。具体规则与 Broker Load 一致。
这块是自动换行

2022-04-06 08:01 UTC, LittleBeeBee commented on loading/RoutineLoad.md
> +~~~json
json这一章节之前讨论是删掉？

2022-04-06 11:54 UTC, jaogoy requested changes

2022-04-06 11:54 UTC, jaogoy commented on loading/SparkLoad.md
>   LoadStartTime: 2019-07-27 11: 49: 44
数据中的内容你对比下修改前的，这块的内容不需要修改的（保留 client 输出的即可）

2022-04-12 06:00 UTC, jaogoy commented on loading/SparkLoad.md
>  导入任务的标识。每个导入任务，都有一个在单 database 内部唯一的 Label。具体规则与 Broker Load 一致。
看下预览啊，这个格式和之前的不一样啊（保持统一）

2022-04-12 06:03 UTC, jaogoy commented on loading/SparkLoad.md
> +使用 Spark Load 时没有在 Spark 客户端的 spark-env.sh 配置 HADOOP-CONF-DIR 环境变量。
这块 Q/A的格式统一下，至少和其他几个 Load 保持一致。
@hellolilyliuyi 这块要求也定一下

2022-05-13 13:12 UTC, jaogoy commented on loading/RoutineLoad.md
> +  * desireTaskConcurrentNum： desired_concurrent_number 配置
给个链接指向具体解释

2022-05-13 13:12 UTC, jaogoy commented on loading/RoutineLoad.md
> +  * max_routine_load_task_concurrent_num：be.conf 配置项，默认为5
同上

2022-05-13 13:12 UTC, jaogoy commented on loading/RoutineLoad.md
> +~~~sql
你们确定下，到底用什么。
个人感觉，用了 sql，这个结果就花花绿绿的

2022-05-13 13:12 UTC, jaogoy commented on loading/RoutineLoad.md
> +  "desired_concurrent_number" = "10"
统一“四个空格"缩进

2022-05-13 13:12 UTC, jaogoy commented on loading/RoutineLoad.md
> +  "desired_concurrent_number" = "3",
四空格

2022-05-13 13:12 UTC, jaogoy commented on loading/RoutineLoad.md
> +  {
这个统一四空格或 2 空格，不要有的 2 有的 4

2022-05-13 13:12 UTC, jaogoy commented on loading/SparkLoad.md
> +使用 Spark Load导入数据，需要按照 `创建资源-->配置 Spark 客户端-->配置 YARN 客户端-->创建 Spark Load 导入任务` 流程执行，具体的各个部分介绍请参考下问描述。
可以统一下，
我个人倾向于 aaaa -> bbbb (或者 aaaa --> bbbb), 箭头两边加空格

2022-05-13 13:12 UTC, jaogoy commented on loading/SparkLoad.md
> +    show resources;
不需要缩进吧

2022-05-13 13:12 UTC, jaogoy commented on loading/SparkLoad.md
> +**示例 3**：上游数据源是 hive 表的情况
从上面摘到下面，有什么排序原因么？

（如果没有的话，尽量和之前保持小的差异，review 方便）

2022-05-13 13:12 UTC, jaogoy commented on loading/SparkLoad.md
> +    CANCEL LOAD FROM db1 WHERE LABEL = "label1";
不需要缩进吧

2022-05-13 13:12 UTC, jaogoy commented on loading/SparkLoad.md
> +1、报错：When running with master 'yarn' either HADOOP-CONF-DIR or YARN-CONF-DIR must be set in the environment.
1. 其他地方有 Q：xxx  \n   A: yyy 。是否搞成统一？
2. A: yyy 是否缩进？

2022-05-14 04:11 UTC, jaogoy commented on loading/RoutineLoad.md
> +        {
这个也统一四空格？

2022-05-14 04:11 UTC, jaogoy commented on loading/SparkLoad.md
> +A：使用 Spark Load 时没有在 Spark 客户端的 spark-env.sh 配置 HADOOP-CONF-DIR 环境变量。
这里也一样

2022-05-14 07:56 UTC, jaogoy approved these changes

2022-05-14 10:59 UTC, merged