add bitmap_max/bitmap_min
StarRocks/docs.zh-cn pull request #374
Opened 2022-04-02 13:50 UTC by hellolilyliuyi

2022-04-05 11:58 UTC, jaogoy requested changes

2022-04-05 11:58 UTC, jaogoy commented on sql-reference/sql-functions/bitmap-functions/bitmap_max.md
> +`bitmap_expr`：Bitmap的表达式，可以由 BITMAP_FROM_STRING 等函数构造。
链接

2022-04-05 11:58 UTC, jaogoy commented on sql-reference/sql-functions/bitmap-functions/bitmap_max.md
> +返回 BIGINT 类型的值。
确定返回 BIGINT 么

2022-04-05 11:58 UTC, jaogoy commented on sql-reference/sql-functions/bitmap-functions/bitmap_min.md
> ++-------------------------------------------------+
还是 max()

2022-04-05 11:58 UTC, jaogoy commented on sql-reference/sql-functions/bitmap-functions/bitmap_min.md
> +`bitmap_expr`：Bitmap的表达式，可以由 BITMAP_FROM_STRING 等函数构造。
BITMAP_FROM_STRING 搞成链接

2022-04-06 09:18 UTC, hellolilyliuyi commented on sql-reference/sql-functions/bitmap-functions/bitmap_max.md
> +返回 BIGINT 类型的值。
这个经过凯森确认的，在群「array函数、bitmap函数--文档沟通」
![截屏2022-04-06 下午5 18 36](https://user-images.githubusercontent.com/96421222/161941808-d6652a65-7e94-429e-946b-20b3f6231e9a.png)
中

2022-04-06 11:13 UTC, jaogoy submitted a review, later dismissed

2022-04-06 11:39 UTC, jaogoy approved these changes

2022-04-08 04:31 UTC, jaogoy approved these changes

2022-04-20 12:06 UTC, merged