update data-type
StarRocks/docs.zh-cn pull request #383
Opened 2022-04-06 14:10 UTC by dq1201

2022-04-06 14:58 UTC, jaogoy requested changes

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/Utility/DESCRIBE.md
> +## 关键字 (keywords)
统一一下，是否保留 keywords 这个单词

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/BIGINT.md
> +  pk BIGINT(20) NOT NULL COMMENT ""
() 内的，统一4空格锁进。
后续代码块相关的，一般都要注意风格，统一缩进4空格

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/BIGINT.md
> +  pk BIGINT(20) NOT NULL COMMENT ""
下面的，也都需要修改下

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/CHAR.md
> +    pk       INT        COMMENT "range [-2147483648, 2147483647]",
注意空格，保持和其他代码块一致

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/CHAR.md
> +    pk       INT        COMMENT "range [-2147483648, 2147483647]",
还有下面的一些

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/DATE.md
> +### DATE 函数
函数写到函数的地方，这里可以做个链接简单说明

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/DATE.md
>  mysql> SELECT DATE('2003-12-31 01:02:03');
一行的返回结果的格式，也统一下，文档方面的规范都可以问刘艺

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/DATETIME.md
> +打印的形式是'YYYY-MM-DD HH: MM: SS'
注意冒号后面的空格，都统一处理下。
后续用这个工具加空格时，都review下变动

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/DECIMAL.md
> +1.19.0 版本可成功执行 `select cast（‘12.35’ as decimal）;` 1.19 之前版本执行 `select cast（‘12.35’ as decimal）;` 或者 `select cast（‘12.35’ as decimal（5））;` 会提示 failed，需明确指定 p, s 的值, 如：`select cast（‘12.35’ as decimal（5
注意P、S保持统一大写

2022-04-06 14:58 UTC, jaogoy commented on sql-reference/sql-statements/data-types/DECIMAL.md
> +  1. 内部采用多种宽度的整数表示 decimal, decimal(P <= 18, S)使用 64bit 整数, 相比于原来 decimal v2 实现统一采用 128bit 整数, 算数运算和转换运算在 64bit 的处理器上使用更少的指令数量, 因此性能有大幅提升。
decimal v2？ 连起来吧？

2022-04-20 11:52 UTC, dq1201 commented on sql-reference/sql-statements/Utility/DESCRIBE.md
> +## 关键字 (keywords)
这个后续我统一改一下

2022-04-22 09:28 UTC, hellolilyliuyi approved these changes

2022-04-22 10:59 UTC, jaogoy approved these changes

2022-04-22 11:00 UTC, merged