地理函数文档优化
StarRocks/docs.zh-cn pull request #385
Opened 2022-04-07 03:41 UTC by Lunmer

2022-04-21 08:31 UTC, ss892714028 requested changes

2022-04-21 08:31 UTC, ss892714028 commented on sql-reference/sql-functions/spatial-functions/st_point.md
> +> 直接 select ST_Point()会卡住, 慎重！！！
Use formal language, and explain why this would cause `select` statement freezes.

2022-04-24 09:00 UTC, Lunmer commented on sql-reference/sql-functions/spatial-functions/st_point.md
> +> 直接 select ST_Point()会卡住, 慎重！！！
这里我去掉了，其余的都修改了，请帮忙review

2022-04-26 08:54 UTC, ss892714028 approved these changes

2022-04-26 11:58 UTC, ss892714028 approved these changes

2022-04-29 04:24 UTC, merged