文档需求列表
StarRocks/docs.zh-cn pull request #433
Opened 2022-04-18 12:29 UTC by Yuchen914

2022-04-24 03:04 UTC, chaoyangqi submitted a review, later dismissed
see see

2022-04-24 03:04 UTC, chaoyangqi commented on using_starrocks/Bloomfilter_index.md
> +* 不支持对Tinyint、Float、Double、Decimal 等类型的列创建Bloom Filter索引。
没有其他类型不支持的话把等删了把

2022-04-24 03:20 UTC, chaoyangqi commented on sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
> +* step2: 计算大概的导入时间是否超过默认 timeout 值，导入时间 ≈ 15000 / 10 = 1500s，超过了默认的 timeout 时间，需要修改 FE 的配置FE.conf：
be/fe参数确认是否重启生效，还是说热修改可以

2022-05-06 15:36 UTC, jaogoy requested changes

2022-05-06 15:36 UTC, jaogoy commented on loading/BrokerLoad.md
> +Broker Load是一种*异步**的导入方式**，该导入通过部署的Broker程序，StarRocks可读取对应数据源（如HDFS、S3）上的数据，利用自身的计算资源对数据进行预处理和导入。因为是异步导入，所以用户需要通过MySQL协议创建导入，并通过查看导入命令检查导入结果。
*异步**的导入方式**
这个格式有问题

2022-05-06 15:36 UTC, jaogoy commented on loading/BrokerLoad.md
> +本节主要介绍Broker导入的及常见问题。
“导入的及常见问题”？

2022-05-06 15:36 UTC, jaogoy commented on loading/BrokerLoad.md
> +Broker Load是一种*异步**的导入方式**，该导入通过部署的Broker程序，StarRocks可读取对应数据源（如HDFS、S3）上的数据，利用自身的计算资源对数据进行预处理和导入。因为是异步导入，所以用户需要通过MySQL协议创建导入，并通过查看导入命令检查导入结果。
该导入xxx，这句话也不大通顺啊。

去掉“该导入”？

2022-05-06 15:36 UTC, jaogoy commented on loading/BrokerLoad.md
> +Broker Load是一种*异步**的导入方式**，该导入通过部署的Broker程序，StarRocks可读取对应数据源（如HDFS、S3）上的数据，利用自身的计算资源对数据进行预处理和导入。因为是异步导入，所以用户需要通过MySQL协议创建导入，并通过查看导入命令检查导入结果。
“所以用户需要通过MySQL协议创建”？

难道同步的导入，就不需要MySQL协议？这个没有联系吧。
直接说：通过SQL异步创建导入作业后，可以通过 `show load`命令检查导入的结果。

2022-05-06 15:36 UTC, jaogoy commented on loading/BrokerLoad.md
> +Broker Load支持从Apache HDFS、Amazon S3等外部存储系统导入数据，支持CSV、ORCFile、Parquet等文件格式。数据量在几十GB到上百GB 级别。
数据量不在几十GB到几百GB到，就不能用么？

这个话讲得不太清楚

2022-05-06 15:36 UTC, jaogoy commented on loading/BrokerLoad.md
这个“语法”是干嘛的呢

2022-05-06 15:36 UTC, jaogoy commented on loading/StreamLoad.md
这里同步的导入方式，为什么没有同上面一样，用斜体或粗体？

2022-05-06 15:36 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
>      ```bash
尾部有 \，后面就要换行，你预览下

2022-05-06 15:36 UTC, jaogoy commented on loading/StreamLoad.md
> +可以参考 [STREAM LOAD](../sql-reference/sql-statements/data-manipulation/STREAM%20LOAD.md)
为什么最佳实践放reference中去

2022-05-06 15:36 UTC, jaogoy commented on table_design/Data_distribution.md
> +Hash分桶一旦确定，分桶数也就随之固定，不能再进行调整。
可以修改的，新分区就会采用新的默认的分桶数

2022-05-06 15:36 UTC, jaogoy commented on table_design/Data_distribution.md
> +动态分区可参考下方文档动态分区管理。
可以直接用链接

2022-05-06 15:36 UTC, jaogoy commented on table_design/Data_distribution.md
> +* 分桶的数量影响查询的并行度，最佳实践是计算一下数据存储量，将每个tablet设置成 100MB ~ 1GB 之间。
这段100MB～1GB我哪里有改过，你看下那边的，保持统一

2022-05-06 15:36 UTC, jaogoy commented on using_starrocks/Materialized_view copy.md
> +3. Materialized Views 表：简称 MVs，翻译：物化视图。
不需要“翻译”两字吧

2022-05-09 11:35 UTC, EsoragotoSpirit requested changes

2022-05-09 11:35 UTC, EsoragotoSpirit commented on table_design/Data_distribution.md
> +* 选择**高基数的列**来作为分桶键（如果有唯一ID就用这个列来作为 分桶键 即可），这样保证数据在各个bucket中尽可能均衡，如果碰到数据倾斜严重的，数据可以使用多列作为分桶键（但一般不要太多）。
选择**高基数的列**（例如唯一ID）来作为分桶键，可以保证数据在各个bucket中尽可能均衡。如果数据倾斜情况严重，用户可以使用多个列作为数据的分桶键，但是不建议使用过多列。

2022-05-09 11:35 UTC, EsoragotoSpirit commented on table_design/Data_distribution.md
> +* 在机器比较少的情况下，如果想充分利用机器资源可以考虑使用 ` BE数量 * cpu core / 2 `来设置bucket数量。例如有100GB的CSV文件(未压缩)，导入StarRocks，有4台BE，每台64C，只有一个分区，那么可以采用 bucket数量 `4 * 64 /2  = 128`，这样每个tablet的数据也在781MB，同时也能充分利用CPU资源。
在机器资源不足的情况下，用户如果想充分利用机器资源，可以通过 ` BE数量 * cpu core / 2 `的计算方式来设置bucket数量。例如，在将 100GB 未压缩的 CSV 文件导入 StarRocks 时，用户使用 4 台 BE，每台包含 64 核心，仅建立一个分区，通过以上计算方式可得出 bucket 数量为 `4 * 64 /2  = 128`。此时每个 tablet 的数据为 781MB，能够充分利用CPU资源。

2022-05-09 11:35 UTC, EsoragotoSpirit commented on table_design/Data_distribution.md
> +在StarRocks系统中，分桶是实际物理文件组织的单元。数据在写入磁盘后，就会涉及磁盘文件的管理。一般而言，我们不建议分桶数据过大或过小，尽量适中会比较妥当。
“一般而言，我们不建议分桶数据过大或过小，尽量适中会比较妥当。”

此处的过大过小是相对于什么而言？如果没有具体参照这句话并没有任何意义，建议删去。

如果参照是指下文的集群规模和机器数量的变化，也可以将这句话删去。

2022-05-09 11:35 UTC, EsoragotoSpirit commented on table_design/Data_distribution.md
> +在'采用Range-Hash组合分布的建表语句' 中，site\_access采用site\_id作为分桶键, 这里选用site\_id字段作为分桶键的原因在于，针对site\_access表的查询请求，基本上都以站点作为查询过滤条件。采用site\_id作为分桶键，可以在查询时裁剪掉大量无关分桶。如下案例中的查询，可以裁剪掉10个bucket中的9个，只需要扫描site\_access表的1/
在 '采用Range-Hash组合分布的建表语句' 示例中，site\_access 采用 site\_id 作为分桶键，其原因在于，针对site\_access表的查询请求，基本上都以站点作为查询过滤条件。采用site\_id作为分桶键，可以在查询时裁剪掉大量无关分桶。如下案例中的查询，10个bucket中的9个被裁减，因而系统只需要扫描site\_access表的1/10的数据。

2022-05-09 11:35 UTC, EsoragotoSpirit commented on table_design/Data_distribution.md
> +但是存在这样一种情况，假设site\_id分布十分不均匀，大量的访问数据是关于少数网站的（幂律分布, 二八规则）。如果用户依然采用上述分桶方式，数据分布会出现严重的数据倾斜, 导致系统局部的性能瓶颈。这个时候，用户需要适当调整分桶的字段，以将数据打散，避免性能问题。如下案例中，可以采用site\_id、city\_code组合作为分桶键，将数据划分得更加均匀。
但假如site\_id分布十分不均匀，大量的访问数据是关于少数网站的（幂律分布, 二八规则），如果用户依然采用上述分桶方式，数据分布会出现严重的倾斜，进而导致系统局部的性能瓶颈。

2022-05-17 06:17 UTC, EsoragotoSpirit approved these changes

2022-05-17 12:04 UTC, EsoragotoSpirit approved these changes

2022-05-18 03:15 UTC, jaogoy commented on loading/BrokerLoad.md
> +* **Apache HDFS导入示例：**
这两个导入示例，和下面的参数的，如“多表导入”等，都一个级别么？
看下 review，感觉不是很清晰直观

2022-05-18 03:15 UTC, jaogoy commented on sql-reference/sql-statements/data-manipulation/BROKER LOAD.md
> +5. 百度BOS：百度对象存储。
什么原因，又加会来了？

2022-05-18 03:15 UTC, jaogoy commented on table_design/Data_distribution.md
> -Hash分桶一旦确定，分桶数也就随之固定，不能再进行调整。
这个可以保留，然后再加上，只能设置未创建的分区的分桶数。

2022-05-18 03:15 UTC, jaogoy commented on table_design/Data_distribution.md
> +* 在机器资源不足的情况下，用户如果想充分利用机器资源，可以通过 BE数量 \* cpu core / 2的计算方式来设置bucket数量。例如，在将 100GB 未压缩的 CSV 文件导入 StarRocks 时，用户使用 4 台 BE，每台包含 64 核心，仅建立一个分区，通过以上计算方式可得出 bucket 数量为 4 \* 64 /2 = 128。此时每个 tablet 的数据为 781
函数/表达式使用、路径、配置 等，可以换统一用反引号。
这块你们交流统一下

2022-05-18 03:15 UTC, jaogoy commented on table_design/Data_distribution.md
> +StarRocks支持自动增删分区之后表的分区，调度的时机依赖于FE的配置，FE的常驻线程会根据dynamic\_partition\_enable和dynamic\_partition\_check\_interval\_seconds两个参数来控制。每次调度时，读取动态分区表的属性，以此判断是否增加/删除分区。
“StarRocks支持自动增删分区之后表的分区” 什么意思？

2022-05-18 03:39 UTC, Yuchen914 commented on table_design/Data_distribution.md
> +* 在机器资源不足的情况下，用户如果想充分利用机器资源，可以通过 BE数量 \* cpu core / 2的计算方式来设置bucket数量。例如，在将 100GB 未压缩的 CSV 文件导入 StarRocks 时，用户使用 4 台 BE，每台包含 64 核心，仅建立一个分区，通过以上计算方式可得出 bucket 数量为 4 \* 64 /2 = 128。此时每个 tablet 的数据为 781
好的

2022-05-19 05:58 UTC, jaogoy submitted a review, later dismissed

2022-05-19 08:46 UTC, EsoragotoSpirit approved these changes

2022-05-19 08:46 UTC, merged