[Doc] add auth to aws resources and catalog docs
StarRocks/docs.zh-cn pull request #4474
Opened 2023-02-16 12:15 UTC by amber-create

Signed-off-by: amber-create <yangyanping@starrocks.com>

2023-02-17 02:10 UTC, EsoragotoSpirit requested changes

2023-02-17 02:10 UTC, EsoragotoSpirit commented on integrations/authenticate_to_aws_resources.md
> +必须在 Internal Catalog `default_catalog` 中创建文件外部表。 以下示例在现有数据库 `test_s3_db` 上创建了一个名为 `file_table` 的文件外部表。有关详细的语法和参数说明，参见 [文件外部表](../data_source/file_external_table.md)。
第一个句号后多了个空格

2023-02-17 07:20 UTC, evelynzhaojie approved these changes

2023-02-17 13:06 UTC, evelynzhaojie approved these changes

2023-02-20 01:20 UTC, merged

2023-02-20 01:20 UTC, amber-create commented
@mergify backport 2.5