update existing privilege  in doc for 3.0
StarRocks/docs.zh-cn pull request #5193
Opened 2023-04-26 11:33 UTC by evelynzhaojie

2023-04-26 12:39 UTC, wangsimo0 requested changes
留了一些comment

2023-04-26 12:39 UTC, wangsimo0 commented on sql-reference/sql-statements/account-management/CREATE ROLE.md
> +> 只有拥有 System 级 GRANT 权限或拥有 `user_admin` 角色的用户才可以创建角色。
因为system的grant权限是不可以授予给别人的，跟user admin绑死的，所以这里就写user admin就行

2023-04-26 12:39 UTC, wangsimo0 commented on sql-reference/sql-statements/account-management/DROP ROLE.md
> +> - 用户可以删除自己创建的角色，但是只有拥有 `user_admin` 角色的用户才可以删除其他角色。更多权限说明，参见 [GRANT](/sql-reference/sql-statements/account-management/GRANT.md)。
只有user admin可以删除角色。

2023-04-26 12:39 UTC, wangsimo0 commented on sql-reference/sql-statements/account-management/GRANT.md
> +> 只有拥有 `user_admin` 角色的用户才可以将任意权限授予给任意用户和角色。
普通用户可以将自身拥有的授权中带有with grant option关键字的权限赋予给其他用户和角色。

2023-04-26 12:39 UTC, wangsimo0 commented on sql-reference/sql-statements/account-management/SET PASSWORD.md
> +> - 只有 `user_priv` 角色才可以修改其他用户的密码。
user admin

2023-04-26 12:39 UTC, wangsimo0 commented on sql-reference/sql-statements/data-definition/DROP MATERIALIZED VIEW.md
> +> 只有拥有基表所在数据库 DROP 权限的用户才可以删除对应物化视图。
对应物化视图的drop权限

2023-04-28 03:16 UTC, wangsimo0 requested changes
leave some additional comment

2023-04-28 03:16 UTC, wangsimo0 commented on sql-reference/sql-statements/account-management/REVOKE.md
> +> 只有拥有 `user_admin` 角色的用户才可以执行该操作。
- 普通用户可以将自身拥有的授权中带有 with grant option 关键字的权限从其他用户或角色处收回

2023-04-28 03:16 UTC, wangsimo0 commented on using_starrocks/Colocate_join.md
> +该 API 在 FE 端实现，您可以使用 `fe_host:fe_http_port` 进行访问。访问需要 `cluster_admin` 角色对应的权限。
root

2023-04-28 10:24 UTC, EsoragotoSpirit approved these changes

2023-04-28 10:26 UTC, hellolilyliuyi approved these changes

2023-04-28 10:52 UTC, wangsimo0 approved these changes
LGTM

2023-04-28 14:57 UTC, merged

2023-04-28 14:57 UTC, evelynzhaojie commented
@mergify backport 3.0