Add hive meta cache to hive catalog
StarRocks/docs.zh-cn pull request #5349
Opened 2023-05-15 03:22 UTC by amber-create

2023-05-16 02:23 UTC, stephen-shelby commented on data_source/catalog/hive_catalog.md
> +| enable_cache_list_names                | 否       | 指定 StarRocks 是否缓存 Hive Partition Names。取值范围：`true` 和 `false`。默认值：`false`。取值为 `true` 表示开启缓存，取值为 `false` 表示关闭缓存。 |
After 3.0, the default value is `true`

2023-05-16 02:23 UTC, stephen-shelby commented on data_source/catalog/hive_catalog.md
> +  > 自 2.5.5 版本起，StarRocks 支持周期性刷新 Hive 元数据。开启 Hive 元数据周期性刷新功能以后，默认情况下 StarRocks 每 10 分钟刷新一次 Hive 元数据。因此，一般情况下，无需执行手动更新。您只有在新增分区后，需要立即查询新增分区的数据时，才需要执行手动更新。
`周期性刷新Hive元数据缓存` may be more precise

2023-05-16 02:23 UTC, stephen-shelby commented on data_source/catalog/hudi_catalog.md
> +以下情况适用于执行手动更新元数据：
hudi先不用写这些，后面可能会修改，这些只在hive catalog里面先放着。

2023-05-16 02:45 UTC, Youngwb commented on data_source/catalog/hive_catalog.md
> +| enable_background_refresh_connector_metadata                 | v3.0 为 true，v2.5 为 false   | 是否开启 Hive 元数据周期性刷新。开启后，StarRocks 通过轮询经常访问的 Hive 外部数据目录的 Hive Metastore 感知数据更新，并将信息缓存至对应外部数据目录的元数据中。`true`
This is mutable

2023-05-16 02:50 UTC, Youngwb commented on data_source/catalog/hudi_catalog.md
> +| enable_cache_list_names                | 否       | 指定 StarRocks 是否缓存 Hive Partition Names。取值范围：`true` 和 `false`。默认值：`false`。取值为 `true` 表示开启缓存，取值为 `false` 表示关闭缓存。 |
```suggestion
| enable_cache_list_names                | 否       | 指定 StarRocks 是否缓存 Hudi Partition Names。取值范围：`true` 和 `false`。默认值：`false`。取值为 `true` 表示开启缓存，取值为 `false` 表示关闭缓存。 |
```

2023-05-17 02:29 UTC, amber-create commented on data_source/catalog/hive_catalog.md
> +| enable_cache_list_names                | 否       | 指定 StarRocks 是否缓存 Hive Partition Names。取值范围：`true` 和 `false`。默认值：`false`。取值为 `true` 表示开启缓存，取值为 `false` 表示关闭缓存。 |
A new PR will be submitted for 3.0

2023-05-18 06:36 UTC, EsoragotoSpirit requested changes

2023-05-18 06:36 UTC, EsoragotoSpirit commented on data_source/catalog/hive_catalog.md
> +默认情况下，StarRocks 会缓存 Hive 的元数据、并以异步模式自动更新缓存的元数据，从而提高查询性能。此外，在对 Hive 表做了表结构变更、或其他表更新后，您也可以使用 [REFRESH EXTERNAL TABLE](../../sql-reference/sql-statements/data-definition/REFRESH%20EXTERNAL%20TABLE.md) 手
![image](https://github.com/StarRocks/docs.zh-cn/assets/104624482/c1cc9703-c198-493b-b334-8ead90ca0e78)
顿号可删

2023-05-18 06:39 UTC, EsoragotoSpirit approved these changes

2023-05-18 06:49 UTC, merged

2023-05-18 06:50 UTC, amber-create commented
@mergify backport 3.0 2.5