Update Using_bitmap.md
StarRocks/docs.zh-cn pull request #546
Opened 2022-05-09 02:48 UTC by 311709000529

Update Using_bitmap.md

2022-05-12 08:05 UTC, EsoragotoSpirit requested changes

2022-05-12 08:05 UTC, EsoragotoSpirit commented on using_starrocks/Using_bitmap.md
> +显然，上面的计算方式，由于数据需要进行多次shuffle，当数据量越来越大时，所需的计算资源就会越来越多，查询也会越来越慢。使用[Bitmap技术](#使用Bitmap去重)，就是为了解决传统count distinct在大量数据场景下的性能问题。
显然，在上面的计算方式中农，由于数据需要进行多次 shuffle，当数据量越来越大时，所需的计算资源就会越来越多，查询也会越来越慢。而使用 Bitmap 技术去重，就是为了解决传统 count distinct 在大量数据场景下的性能问题。

2022-05-16 02:34 UTC, 311709000529 commented on using_starrocks/Using_bitmap.md
>  2 row in set (0.00 sec)
这块对用户会不会不太友好？

2022-05-17 06:59 UTC, EsoragotoSpirit approved these changes

2022-05-17 07:25 UTC, merged