Update Using_HLL.md
StarRocks/docs.zh-cn pull request #547
Opened 2022-05-09 02:50 UTC by 311709000529

Update Using_HLL.md

2022-05-12 09:18 UTC, EsoragotoSpirit requested changes

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
> +Bitmap 只支持 TINYINT，SMALLINT，INT，BIGINT，(注意不支持 LARGEINT )，对其他类型数据集去重，则需要构建词典，将原类型映射到整数类型。词典构建比较复杂，需要权衡数据量，更新频率，查询效率，存储等一系列问题. HLL 则没有必要构建词典，只需要对应的数据类型支持哈希函数即可，甚至在没有内部支持 HLL 的分析系统中，依然可以使用系统提供的 hash，用 S
* Bitmap 仅支持 TINYINT，SMALLINT，INT，BIGINT（注意不支持 LARGEINT）去重。对于其他类型数据集去重，用户需要构建词典，将原类型映射到整数类型。词典构建较复杂，需要权衡数据量，更新频率，查询效率，存储等一系列问题。HLL 去重方式则无需构建词典，仅要求对应的数据类型支持哈希函数。即便在没有内部支持 HLL 的分析系统中，依然可以使用系统提供的 hash，用 SQL 实现 HLL 去重。

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
> +Bitmap 只支持 TINYINT，SMALLINT，INT，BIGINT，(注意不支持 LARGEINT )，对其他类型数据集去重，则需要构建词典，将原类型映射到整数类型。词典构建比较复杂，需要权衡数据量，更新频率，查询效率，存储等一系列问题. HLL 则没有必要构建词典，只需要对应的数据类型支持哈希函数即可，甚至在没有内部支持 HLL 的分析系统中，依然可以使用系统提供的 hash，用 S
Bitmap 仅支持 TINYINT，SMALLINT，INT，BIGINT（注意不支持 LARGEINT）去重。对于其他类型数据集去重，用户需要构建词典，将原类型映射到整数类型。词典构建较复杂，需要权衡数据量，更新频率，查询效率，存储等一系列问题。HLL 去重方式则无需构建词典，仅要求对应的数据类型支持哈希函数。即便在没有内部支持 HLL 的分析系统中，依然可以使用系统提供的 hash，用 SQL 实现 HLL 去重。

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
>  #### 示例
`### 示例`

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
>  #### 示例
`### 示例`

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
>  ### 注意事项
`## 选择去重方案`

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
>  ### 注意事项
`## 选择去重方案`

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
> +对于普通列，用户还可以使用 NDV 函数进行近似去重计算。NDV函数返回值是COUNT(DISTINCT col) 结果的近似值聚合函数，底层实现将数据存储类型转为 HyperLogLog 类型进行计算。NDV 函数在计算的时候比较消耗资源，不太适合并发高的场景。
* 对于普通列，用户还可以使用 NDV 函数进行近似去重计算。NDV 函数返回值是 COUNT(DISTINCT col) 结果的近似值聚合函数，底层实现将数据存储类型转为 HyperLogLog 类型进行计算。但 NDV 函数在计算的时候比较消耗资源，不适合于并发高的场景。

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
> +对于普通列，用户还可以使用 NDV 函数进行近似去重计算。NDV函数返回值是COUNT(DISTINCT col) 结果的近似值聚合函数，底层实现将数据存储类型转为 HyperLogLog 类型进行计算。NDV 函数在计算的时候比较消耗资源，不太适合并发高的场景。
* 对于普通列，用户还可以使用 NDV 函数进行近似去重计算。NDV 函数返回值是 COUNT(DISTINCT col) 结果的近似值聚合函数，底层实现将数据存储类型转为 HyperLogLog 类型进行计算。但 NDV 函数在计算的时候比较消耗资源，不适合于并发高的场景。

2022-05-12 09:18 UTC, EsoragotoSpirit commented on using_starrocks/Using_HLL.md
>  如果您希望进行用户行为分析，可以考虑 IntersectCount 或者自定义 UDAF。
* 如果应用场景为用户行为分析，建议使用 IntersectCount 或者自定义 UDAF 去重。

2022-05-16 03:09 UTC, 311709000529 commented on using_starrocks/Using_HLL.md
>  ### 注意事项
此处不只是 **选择去重方案**  的描述。

2022-05-16 03:10 UTC, 311709000529 commented on using_starrocks/Using_HLL.md
> +## 什么是 HyperLogLog
目前 还没有特定章节来放这些东西，后续其他章节有了的话，可以引链下，目前最好还是放在这里吧。

2022-05-17 06:58 UTC, EsoragotoSpirit approved these changes

2022-05-17 07:25 UTC, merged