3.1 random distribution
StarRocks/docs.zh-cn pull request #5876
Opened 2023-06-30 02:32 UTC by hellolilyliuyi

2023-07-04 11:45 UTC, amber-create commented on sql-reference/sql-statements/data-definition/CREATE TABLE.md
> +  * 不支持主键模型的表、更新模型的表和聚合表。
![image](https://github.com/StarRocks/docs.zh-cn/assets/57167462/b7545ad3-65d6-41c5-9927-8bffd46e9b81)
两个“的”去掉吧

2023-07-04 11:48 UTC, amber-create commented on table_design/Data_distribution.md
> +如下查询中，假设每个分区有 10 个分桶，则其中 9 个分桶被裁减，因而系统只需要扫描 site_access 表中 1/10 的数据：
![image](https://github.com/StarRocks/docs.zh-cn/assets/57167462/b53681d8-4c67-463a-86ea-8475dcbf9d26)
加 code format

2023-07-04 11:49 UTC, amber-create commented on table_design/Data_distribution.md
> +- 不支持主键模型的表、更新模型的表和聚合表。
![image](https://github.com/StarRocks/docs.zh-cn/assets/57167462/bc9e8682-eb63-42cd-9a60-2934d0cacebd)
同前，两个“的”删掉

2023-07-05 13:39 UTC, amber-create approved these changes

2023-07-06 03:00 UTC, jaogoy requested changes
有了随机分桶，示例中一些是不是就直接默认不写，或者偶尔用 by random，偶尔指定hash？

2023-07-06 05:03 UTC, hellolilyliuyi commented on table_design/Data_distribution.md
> +- Random：将数据随机地分布到多个节点。
random也是常见的数据分布方式吗

2023-07-06 05:59 UTC, hellolilyliuyi commented on table_design/Data_distribution.md
> +- Range+Random 数据分布：表的数据按照分区列值的范围划分成不同分区。同一分区的数据随机分布至不同分桶。
为啥绝大多数情况是根据时间按天分区的？

2023-07-06 06:48 UTC, hellolilyliuyi commented on table_design/Data_distribution.md
> +分区的下一级是分桶，StarRocks 支持[哈希分桶](#哈希分桶)。在同一分区内，分桶键哈希值相同的数据形成 Tablet，Tablet 以多副本冗余的形式存储，是数据均衡和恢复的最⼩单位。Tablet 的副本由一个单独的本地存储引擎管理，数据导入和查询最终都下沉到所涉及的 Tablet 副本上。自 3.1 版本起，StarRocks 还支持[随机分桶](#随机分桶自-31)，建表和新增分区
> StarRocks 支持[随机分桶](#..)（自 3.1 版本起）和[哈希分桶](#...)。 然后再简述两者。
> 
> 也不是”哈希值相同的数据形成 tablet"，而是指：数据按照分桶键划分 tablet 后，所有分桶键的值相同的行会唯一分配到对应的一个 tablet。
> 
> 这里感觉不需要讲副本（否则把事情搞复杂了）

2023-07-06 07:05 UTC, hellolilyliuyi commented on table_design/Data_distribution.md
> +分区的下一级是分桶，StarRocks 支持[哈希分桶](#哈希分桶)。在同一分区内，分桶键哈希值相同的数据形成 Tablet，Tablet 以多副本冗余的形式存储，是数据均衡和恢复的最⼩单位。Tablet 的副本由一个单独的本地存储引擎管理，数据导入和查询最终都下沉到所涉及的 Tablet 副本上。自 3.1 版本起，StarRocks 还支持[随机分桶](#随机分桶自-31)，建表和新增分区
现在咱们文档里面既有tablet 又有bucket，我们是主要使用 tablet还是bucket呢？

2023-07-06 07:09 UTC, hellolilyliuyi commented on table_design/Data_distribution.md
> +分区的下一级是分桶，StarRocks 支持[哈希分桶](#哈希分桶)。在同一分区内，分桶键哈希值相同的数据形成 Tablet，Tablet 以多副本冗余的形式存储，是数据均衡和恢复的最⼩单位。Tablet 的副本由一个单独的本地存储引擎管理，数据导入和查询最终都下沉到所涉及的 Tablet 副本上。自 3.1 版本起，StarRocks 还支持[随机分桶](#随机分桶自-31)，建表和新增分区
哈希分桶的话 分桶键的值相似的数据行也会尽可能被分配至同一个tablet 吗？如果是的话，哈希算法怎么界定「相似」呢

2023-07-06 09:03 UTC, hellolilyliuyi commented on table_design/Data_distribution.md
> +**使用限制**
「使用限制」还是用户浏览多的文档吧，因为很多时候用户不会去看reference

2023-07-06 12:49 UTC, jaogoy commented on table_design/Data_distribution.md
> +(
我们统一风格，把这个 做括号 `(` 放到上一行最后吧。

因为在 create table 等其他地方，都是这个风格。

2023-07-06 12:49 UTC, jaogoy commented on table_design/Data_distribution.md
> +分桶数量：自 2.5.7 版本起，建表和新增分区时可以不设置分桶数量（推荐），由 StarRocks 自动设置分桶数量。更多信息，请参见[确定分桶数量](#确定分桶数量)。
你这里应该先解释：“分桶数量”，一个分区按分桶方式被分成了多个桶，每个桶的数据称之为一个 tablet。自 2.5.7 xxx，您也可以自己设置分桶数量，参见 xxx。

2023-07-06 12:49 UTC, jaogoy commented on table_design/Data_distribution.md
> +- Range+Random 数据分布：表的数据按照分区列值的范围划分成不同分区。同一分区的数据随机分布至不同分桶。
数据一般按天增长。
一把分析时，当天或者最近几天的数据会被分析得更多。

2023-07-06 12:52 UTC, jaogoy commented on table_design/Data_distribution.md
> +- Random：将数据随机地分布到多个节点。
不常见，或者即使开始按 random，系统也会内部重组

2023-07-07 11:19 UTC, jaogoy commented on table_design/Data_distribution.md
> +分桶数量：推荐 由StarRocks 自动设置分桶数量（自 v2.5.7 版本起）。如果分桶数量。更多信息，请参见[确定分桶数量](#确定分桶数量)。
如果需要设置分桶数量

2023-07-07 12:21 UTC, EsoragotoSpirit approved these changes

2023-07-07 12:23 UTC, jaogoy approved these changes

2023-07-07 12:23 UTC, merged

2023-07-07 12:25 UTC, hellolilyliuyi commented
@mergify backport 3.1