Add session variable query_mem_limit
StarRocks/docs.zh-cn pull request #648
Opened 2022-05-23 12:54 UTC by ZiheLiu

2022-05-23 13:10 UTC, Dshadowzh submitted a review, later dismissed
LGTM

2022-05-23 13:47 UTC, kangkaisen commented on administration/Memory_management.md
> +| query_mem_limit | 0 | 单个查询的内存限制。大于 0 时，使用 query_mem_limit 限制查询的内存；否则，使用 exec_mem_limit 限制查询的内存。 |
这里应该个用户一个建议值。 否则用户根本没法设置这个值。

2022-05-24 02:04 UTC, EsoragotoSpirit requested changes

2022-05-24 02:04 UTC, EsoragotoSpirit commented on administration/Memory_management.md
> +| exec_mem_limit| 2147483648| 单个 instance 的内存限制。一个查询可以使用的内存为 instance 数量*exec_mem_limit。query_mem_limit 为 0 时，exec_mem_limit 才生效。 |
建议在说明中加入单位介绍

2022-05-24 02:04 UTC, EsoragotoSpirit commented on administration/Memory_management.md
> +| load_mem_limit| 0| 单个导入任务的内存限制。如果是 0，会取 exec_mem_limit。 |
“如果是 0，会取 exec_mem_limit。”能够将主语和逻辑讲述清楚？“如果此设置项被设置为`0`，系统将会会采用exec_mem_limit 作为内存上限”

2022-05-24 02:04 UTC, EsoragotoSpirit commented on administration/Memory_management.md
> +| query_mem_limit | 0 | 单个查询的内存限制。大于 0 时，使用 query_mem_limit 限制查询的内存；否则，使用 exec_mem_limit 限制查询的内存。建议设置为 34359738368（32GB）以上。 |
同上

2022-05-24 03:36 UTC, EsoragotoSpirit approved these changes

2022-05-24 03:46 UTC, kangkaisen approved these changes

2022-05-24 03:46 UTC, merged