Update ROUTINE LOAD.md
StarRocks/docs.zh-cn pull request #778
Opened 2022-06-06 13:20 UTC by evelynzhaojie

update this sql statement according to jira issue

https://starrocks.atlassian.net/browse/SR-9627

2022-06-07 02:37 UTC, hellolilyliuyi requested changes

2022-06-07 02:37 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
> +- 整型类（TINYINT/SMALLINT/INT/BIGINT/LARGEINT）：1, 1000, 1234
目前数据类型的大的分类已经确定是这样？

2022-06-07 02:37 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
>      <column_name> = column_expression
column_assignment似乎没在下面说明

2022-06-07 02:37 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
json和csv？我看下面有json

2022-06-07 02:37 UTC, hellolilyliuyi commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
>      <column_name> = column_expression
语法末尾加;

2022-06-07 08:21 UTC, evelynzhaojie commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
>      <column_name> = column_expression
OK 已修改

2022-06-07 08:21 UTC, evelynzhaojie commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
> +- 整型类（TINYINT/SMALLINT/INT/BIGINT/LARGEINT）：1, 1000, 1234
是的

2022-06-07 08:21 UTC, evelynzhaojie commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
已添加

2022-06-07 09:07 UTC, hellolilyliuyi submitted a review, later dismissed

2022-06-07 12:19 UTC, wangsimo0 commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
Kafka--> Apache Kafka

2022-06-07 12:20 UTC, wangsimo0 commented on sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
通过不断的-->通过不断地？

2022-07-06 03:01 UTC, amber-create approved these changes

2022-07-06 03:01 UTC, merged